import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:sqflite_common/sqlite_api.dart';

import '../database/capabilities.dart';
import '../migration/migration.dart';
import 'database_mutations.dart';
import 'database_tools.dart';

part 'runtime_output.dart';
part 'runtime_options.dart';
part 'runtime_workflows.dart';

/// Opens the database used by the migration CLI.
typedef SqliteLoomDatabaseOpener = FutureOr<Database> Function();

/// Receives one line of CLI output.
typedef SqliteLoomCliPrinter = void Function(String line);

/// Confirms a destructive command against a human-readable database identity.
typedef SqliteLoomCliConfirmation =
    FutureOr<bool> Function(String command, String databaseDescription);

/// Opens an isolated database for migration rehearsal.
typedef SqliteLoomSandboxOpener = FutureOr<SqliteLoomSandbox> Function();

/// Restores the configured database from a caller-validated backup path.
typedef SqliteLoomRestoreHandler = FutureOr<void> Function(String inputPath);

/// Owns a temporary sandbox database and its cleanup callback.
final class SqliteLoomSandbox {
  const SqliteLoomSandbox({required this.database, required this.cleanup});

  final Database database;
  final FutureOr<void> Function() cleanup;
}

/// Runs an application-owned migration command and returns a stable exit code.
///
/// The project CLI generated by `dart run sqlite_loom init` delegates database
/// commands here so application migrations and database initialization remain
/// ordinary Dart code. The opened database is always closed before returning.
/// Additive insert, import, and copy commands use [allowDataManipulation], which
/// defaults to [allowDestructive] when omitted.
Future<int> runSqliteLoomCli(
  List<String> args, {
  required SqliteLoomDatabaseOpener openDatabase,
  required Iterable<DbMigration> migrations,
  Set<int> retiredVersions = const <int>{},
  bool allowDestructive = false,
  bool? allowDataManipulation,
  bool allowProductionDestructive = false,
  String environment = 'development',
  String databaseDescription = 'configured database',
  SqliteLoomCliConfirmation? confirmDestructive,
  SqliteLoomSandboxOpener? openSandbox,
  SqliteLoomRestoreHandler? restoreDatabase,
  SqliteLoomCliPrinter printLine = print,
}) async {
  final command = args.isEmpty ? 'help' : args.first;
  final json = args.contains('--json');
  final dataManipulationEnabled = allowDataManipulation ?? allowDestructive;
  if (_isHelp(command)) {
    _printHelp(printLine);
    return 0;
  }
  if (command == 'sandbox') {
    return _runSandbox(
      args,
      migrations: migrations,
      opener: openSandbox,
      json: json,
      printLine: printLine,
    );
  }
  if (command == 'db:restore') {
    return _runRestore(
      args,
      handler: restoreDatabase,
      allowDestructive: allowDestructive,
      allowProductionDestructive: allowProductionDestructive,
      environment: environment,
      databaseDescription: databaseDescription,
      confirmation: confirmDestructive,
      json: json,
      printLine: printLine,
    );
  }

  Database? database;
  try {
    database = await openDatabase();
    final migrator = SqliteLoomMigrator(
      database,
      migrations: migrations,
      retiredVersions: retiredVersions,
    );
    final tools = SqliteLoomDatabaseTools(database);
    final mutations = SqliteLoomDatabaseMutations(database, tools);
    switch (command) {
      case 'migrate':
        final through = _readPositiveInt(args, '--to', required: false);
        final stopwatch = Stopwatch()..start();
        final result = await migrator.migrate(through: through);
        stopwatch.stop();
        if (json) {
          _printJson(printLine, {
            'command': command,
            'success': true,
            'applied': result.applied.map(_migrationJson).toList(),
            'durationMs': stopwatch.elapsedMilliseconds,
          });
        } else if (result.applied.isEmpty) {
          printLine('Nothing to migrate.');
        } else {
          for (final migration in result.applied) {
            printLine('Migrated ${migration.version} ${migration.name}');
          }
        }
        return 0;
      case 'status':
        final statuses = await migrator.status();
        if (json) {
          _printJson(printLine, {
            'command': command,
            'success': true,
            'migrations': [
              for (final status in statuses)
                {
                  'version': status.version,
                  'name': status.name,
                  'applied': status.isApplied,
                  'missingFromCode': status.isMissing,
                  'retired': status.isRetired,
                  'batch': status.applied?.batch,
                  'appliedAt': status.applied?.appliedAt.toIso8601String(),
                  'checksum': status.applied?.checksum,
                },
            ],
          });
        } else if (statuses.isEmpty) {
          printLine('No migrations.');
        } else {
          for (final status in statuses) {
            final state = status.isApplied ? 'Y' : 'N';
            final suffix = status.isMissing
                ? ' missing-from-code'
                : status.isRetired
                ? ' retired'
                : '';
            final batch = status.applied?.batch ?? '-';
            printLine(
              '$state batch=$batch version=${status.version} '
              '${status.name}$suffix',
            );
          }
        }
        return 0;
      case 'rollback':
        final steps = _readSteps(args);
        final result = await migrator.rollback(batches: steps);
        _printRollback(command, result, json: json, printLine: printLine);
        return 0;
      case 'redo':
        final steps = _readSteps(args);
        final rollback = await migrator.rollback(batches: steps);
        final migration = await migrator.migrate();
        if (json) {
          _printJson(printLine, {
            'command': command,
            'success': true,
            'rolledBack': rollback.rolledBack.map(_migrationJson).toList(),
            'applied': migration.applied.map(_migrationJson).toList(),
          });
        } else {
          printLine('Rolled back ${rollback.rolledBack.length} migrations.');
          printLine('Migrated ${migration.applied.length} migrations.');
        }
        return 0;
      case 'reset':
      case 'refresh':
      case 'fresh':
        final permitted = await _confirmDestructive(
          command,
          args,
          allowDestructive: allowDestructive,
          allowProductionDestructive: allowProductionDestructive,
          environment: environment,
          databaseDescription: databaseDescription,
          confirmation: confirmDestructive,
          printLine: printLine,
          json: json,
        );
        if (!permitted) return 73;
        if (command == 'reset') {
          final result = await migrator.reset();
          _printRollback(command, result, json: json, printLine: printLine);
        } else if (command == 'refresh') {
          final result = await migrator.refresh();
          if (json) {
            _printJson(printLine, {
              'command': command,
              'success': true,
              'rolledBack': result.rollback.rolledBack
                  .map(_migrationJson)
                  .toList(),
              'applied': result.migration.applied.map(_migrationJson).toList(),
            });
          } else {
            printLine(
              'Rolled back ${result.rollback.rolledBack.length} migrations.',
            );
            printLine(
              'Migrated ${result.migration.applied.length} migrations.',
            );
          }
        } else {
          final result = await migrator.fresh(allowDestructive: true);
          if (json) {
            _printJson(printLine, {
              'command': command,
              'success': true,
              'droppedTables': result.droppedTables,
              'applied': result.migration.applied.map(_migrationJson).toList(),
            });
          } else {
            printLine('Dropped ${result.droppedTables.length} tables.');
            printLine(
              'Migrated ${result.migration.applied.length} migrations.',
            );
          }
        }
        return 0;
      case 'schema:dump':
        final schema = await _schemaDump(database);
        if (json) {
          _printJson(printLine, {
            'command': command,
            'success': true,
            'objects': schema,
          });
        } else if (schema.isEmpty) {
          printLine('Schema is empty.');
        } else {
          for (final object in schema) {
            printLine('${object['sql']};');
          }
        }
        return 0;
      case 'schema:diff':
        return await _runSchemaDiff(
          database,
          migrations: migrations,
          opener: openSandbox,
          json: json,
          printLine: printLine,
        );
      case 'db:inspect':
        final details = await _inspect(database);
        if (json) {
          _printJson(printLine, {
            'command': command,
            'success': true,
            ...details,
          });
        } else {
          for (final entry in details.entries) {
            printLine('${entry.key}: ${entry.value}');
          }
        }
        return 0;
      case 'db:tables':
        final rows = await tools.tables();
        _printRows(command, rows, json: json, printLine: printLine);
        return 0;
      case 'db:describe':
        final table = _readPositional(args, command);
        final description = await tools.describe(table);
        if (json) {
          _printJson(printLine, {
            'command': command,
            'success': true,
            ...description,
          });
        } else {
          _printDescription(description, printLine);
        }
        return 0;
      case 'db:browse':
        final table = _readPositional(args, command);
        final limit = _readBoundedInt(
          args,
          '--limit',
          fallback: 50,
          minimum: 1,
          maximum: 1000,
        );
        final offset = _readBoundedInt(
          args,
          '--offset',
          fallback: 0,
          minimum: 0,
          maximum: 0x7fffffff,
        );
        final rows = await tools.browse(
          table,
          limit: limit,
          offset: offset,
          orderBy: _readString(args, '--order', required: false),
          descending: args.contains('--desc'),
        );
        _printRows(
          command,
          rows,
          json: json,
          printLine: printLine,
          metadata: {'table': table, 'limit': limit, 'offset': offset},
        );
        return 0;
      case 'db:query':
        final sql = await _readSql(args);
        final rows = await tools.readOnlyQuery(sql);
        _printRows(
          command,
          rows,
          json: json,
          csv: args.contains('--csv'),
          printLine: printLine,
        );
        return 0;
      case 'db:explain':
        final sql = await _readSql(args);
        final rows = await tools.explain(sql);
        _printRows(command, rows, json: json, printLine: printLine);
        return 0;
      case 'db:export':
        final table = _readPositional(args, command);
        final output = _readString(args, '--output', required: true)!;
        final format =
            _readString(args, '--format', required: false) ??
            (output.toLowerCase().endsWith('.json') ? 'json' : 'csv');
        if (format != 'csv' && format != 'json') {
          throw ArgumentError.value(format, '--format', 'Must be csv or json');
        }
        final file = File(output);
        if (await file.exists() && !args.contains('--force')) {
          throw ArgumentError(
            '${file.path} already exists. Pass --force to replace it.',
          );
        }
        final rowCount = await _exportTable(tools, table, file, format: format);
        if (json) {
          _printJson(printLine, {
            'command': command,
            'success': true,
            'table': table,
            'format': format,
            'rowCount': rowCount,
            'output': file.path,
          });
        } else {
          printLine('Exported $rowCount rows from $table to ${file.path}');
        }
        return 0;
      case 'db:insert':
        final table = _readPositional(args, command);
        final values = _readValueMap(
          args,
          jsonOption: '--values-json',
          assignmentOption: '--value',
          required: true,
        )!;
        if (args.contains('--dry-run')) {
          await mutations.validateValues(table, values);
          _printMutationResult(
            command,
            json: json,
            printLine: printLine,
            values: {'dryRun': true, 'table': table, 'values': values},
          );
          return 0;
        }
        if (!_allowDataManipulation(
          command,
          enabled: dataManipulationEnabled,
          allowProduction: allowProductionDestructive,
          environment: environment,
          json: json,
          printLine: printLine,
        )) {
          return 73;
        }
        final insertedId = await mutations.insert(table, values);
        _printMutationResult(
          command,
          json: json,
          printLine: printLine,
          values: {'table': table, 'inserted': 1, 'insertedId': insertedId},
        );
        return 0;
      case 'db:update':
      case 'db:delete':
        final table = _readPositional(args, command);
        final where = _readMutationScope(args);
        final updateValues = command == 'db:update'
            ? _readValueMap(
                args,
                jsonOption: '--set-json',
                assignmentOption: '--set',
                required: true,
              )!
            : null;
        if (updateValues != null) {
          await mutations.validateValues(table, updateValues);
        }
        final preview = await mutations.preview(table, where);
        if (args.contains('--dry-run')) {
          _printMutationResult(
            command,
            json: json,
            printLine: printLine,
            values: {
              'dryRun': true,
              'table': table,
              'matched': preview.count,
              'set': updateValues,
              'sampleRows': jsonSafeRows(preview.rows),
            },
          );
          return 0;
        }
        final permitted = await _confirmDestructive(
          command,
          args,
          allowDestructive: allowDestructive,
          allowProductionDestructive: allowProductionDestructive,
          environment: environment,
          databaseDescription: databaseDescription,
          confirmation: confirmDestructive,
          printLine: printLine,
          json: json,
        );
        if (!permitted) return 73;
        final affected = command == 'db:update'
            ? await mutations.update(table, updateValues!, where)
            : await mutations.delete(table, where);
        _printMutationResult(
          command,
          json: json,
          printLine: printLine,
          values: {
            'table': table,
            'matched': preview.count,
            'affected': affected,
          },
        );
        return 0;
      case 'db:truncate':
        final table = _readPositional(args, command);
        final preview = await mutations.preview(table, const {});
        if (args.contains('--dry-run')) {
          _printMutationResult(
            command,
            json: json,
            printLine: printLine,
            values: {'dryRun': true, 'table': table, 'matched': preview.count},
          );
          return 0;
        }
        final permitted = await _confirmDestructive(
          command,
          args,
          allowDestructive: allowDestructive,
          allowProductionDestructive: allowProductionDestructive,
          environment: environment,
          databaseDescription: databaseDescription,
          confirmation: confirmDestructive,
          printLine: printLine,
          json: json,
        );
        if (!permitted) return 73;
        final affected = await mutations.truncate(table);
        _printMutationResult(
          command,
          json: json,
          printLine: printLine,
          values: {'table': table, 'affected': affected},
        );
        return 0;
      case 'db:execute':
        final sql = mutations.validateExecutableSql(await _readSql(args));
        if (args.contains('--dry-run')) {
          _printMutationResult(
            command,
            json: json,
            printLine: printLine,
            values: {'dryRun': true, 'sql': sql},
          );
          return 0;
        }
        final permitted = await _confirmDestructive(
          command,
          args,
          allowDestructive: allowDestructive,
          allowProductionDestructive: allowProductionDestructive,
          environment: environment,
          databaseDescription: databaseDescription,
          confirmation: confirmDestructive,
          printLine: printLine,
          json: json,
        );
        if (!permitted) return 73;
        await mutations.execute(sql);
        _printMutationResult(
          command,
          json: json,
          printLine: printLine,
          values: {'executed': true},
        );
        return 0;
      case 'db:import':
        final table = _readPositional(args, command);
        final input = File(_readString(args, '--input', required: true)!);
        final format =
            _readString(args, '--format', required: false) ??
            (input.path.toLowerCase().endsWith('.json') ? 'json' : 'csv');
        final rows = await readImportRows(input, format: format);
        final dryRun = args.contains('--dry-run');
        if (!dryRun &&
            !_allowDataManipulation(
              command,
              enabled: dataManipulationEnabled,
              allowProduction: allowProductionDestructive,
              environment: environment,
              json: json,
              printLine: printLine,
            )) {
          return 73;
        }
        final result = await mutations.importRows(table, rows, dryRun: dryRun);
        _printMutationResult(
          command,
          json: json,
          printLine: printLine,
          values: {
            'dryRun': dryRun,
            'table': table,
            'format': format,
            'parsed': result.parsed,
            'inserted': result.inserted,
          },
        );
        return 0;
      case 'db:copy':
        final positionals = _readPositionals(args);
        if (positionals.length != 2) {
          throw ArgumentError('db:copy requires source and destination tables');
        }
        if (args.contains('--dry-run')) {
          final preview = await mutations.preview(positionals.first, const {});
          final columns = await mutations.copyColumns(
            positionals.first,
            positionals.last,
          );
          _printMutationResult(
            command,
            json: json,
            printLine: printLine,
            values: {
              'dryRun': true,
              'source': positionals.first,
              'destination': positionals.last,
              'sourceRows': preview.count,
              'columns': columns,
            },
          );
          return 0;
        }
        if (!_allowDataManipulation(
          command,
          enabled: dataManipulationEnabled,
          allowProduction: allowProductionDestructive,
          environment: environment,
          json: json,
          printLine: printLine,
        )) {
          return 73;
        }
        final affected = await mutations.copy(
          positionals.first,
          positionals.last,
        );
        _printMutationResult(
          command,
          json: json,
          printLine: printLine,
          values: {
            'source': positionals.first,
            'destination': positionals.last,
            'inserted': affected,
          },
        );
        return 0;
      case 'db:vacuum':
        await database.execute('VACUUM');
        _printMutationResult(
          command,
          json: json,
          printLine: printLine,
          values: {'completed': true},
        );
        return 0;
      case 'db:integrity':
        final quick = args.contains('--quick');
        final rows = await database.rawQuery(
          'PRAGMA ${quick ? 'quick_check' : 'integrity_check'}',
        );
        final diagnostics = rows
            .expand((row) => row.values)
            .whereType<String>()
            .toList(growable: false);
        final healthy = diagnostics.length == 1 && diagnostics.single == 'ok';
        if (json) {
          _printJson(printLine, {
            'command': command,
            'success': healthy,
            'diagnostics': diagnostics,
          });
        } else {
          for (final diagnostic in diagnostics) {
            printLine(diagnostic);
          }
        }
        return healthy ? 0 : 1;
      case 'db:optimize':
        await database.execute('PRAGMA optimize');
        if (json) {
          _printJson(printLine, {'command': command, 'success': true});
        } else {
          printLine('Database optimization completed.');
        }
        return 0;
      case 'db:backup':
        final output = _readString(args, '--output', required: true)!;
        final capabilities = await loadDbCapabilities(database);
        capabilities.require(DbFeature.vacuumInto);
        await database.execute('VACUUM INTO ?', [output]);
        if (json) {
          _printJson(printLine, {
            'command': command,
            'success': true,
            'output': output,
          });
        } else {
          printLine('Backup created at $output');
        }
        return 0;
      default:
        printLine('Unknown sqlite_loom command: $command');
        _printHelp(printLine);
        return 64;
    }
  } on ArgumentError catch (error) {
    _printFailure(
      command,
      error.message?.toString() ?? '$error',
      json,
      printLine,
    );
    return 64;
  } catch (error) {
    _printFailure(command, '$error', json, printLine);
    return 70;
  } finally {
    await database?.close();
  }
}

Future<bool> _confirmDestructive(
  String command,
  List<String> args, {
  required bool allowDestructive,
  required bool allowProductionDestructive,
  required String environment,
  required String databaseDescription,
  required SqliteLoomCliConfirmation? confirmation,
  required SqliteLoomCliPrinter printLine,
  required bool json,
}) async {
  if (!allowDestructive) {
    _printFailure(
      command,
      '$command is disabled by the application runner.',
      json,
      printLine,
    );
    return false;
  }
  if (environment.toLowerCase() == 'production' &&
      !allowProductionDestructive) {
    _printFailure(
      command,
      '$command is refused in the production environment.',
      json,
      printLine,
    );
    return false;
  }
  if (args.contains('--force')) return true;
  final confirmed = confirmation == null
      ? false
      : await confirmation(command, databaseDescription);
  if (!confirmed) {
    _printFailure(
      command,
      '$command requires --force or interactive confirmation.',
      json,
      printLine,
    );
  }
  return confirmed;
}

bool _allowDataManipulation(
  String command, {
  required bool enabled,
  required bool allowProduction,
  required String environment,
  required bool json,
  required SqliteLoomCliPrinter printLine,
}) {
  if (!enabled) {
    _printFailure(
      command,
      '$command is disabled by the application runner.',
      json,
      printLine,
    );
    return false;
  }
  if (environment.toLowerCase() == 'production' && !allowProduction) {
    _printFailure(
      command,
      '$command is refused in the production environment.',
      json,
      printLine,
    );
    return false;
  }
  return true;
}

Future<List<Map<String, Object?>>> _schemaDump(Database database) async {
  final rows = await database.rawQuery('''
    SELECT type, name, tbl_name, sql
    FROM sqlite_master
    WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
    ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END, name
  ''');
  return rows.map((row) => Map<String, Object?>.unmodifiable(row)).toList();
}

Future<Map<String, Object?>> _inspect(Database database) async {
  final version = await database.rawQuery('SELECT sqlite_version() AS value');
  final pageCount = await database.rawQuery('PRAGMA page_count');
  final pageSize = await database.rawQuery('PRAGMA page_size');
  final journal = await database.rawQuery('PRAGMA journal_mode');
  final foreignKeys = await database.rawQuery('PRAGMA foreign_keys');
  final tables = await database.rawQuery(
    "SELECT COUNT(*) AS value FROM sqlite_master WHERE type = 'table' "
    "AND name NOT LIKE 'sqlite_%'",
  );
  return {
    'sqliteVersion': version.single['value'],
    'tableCount': tables.single['value'],
    'pageCount': pageCount.single.values.first,
    'pageSize': pageSize.single.values.first,
    'journalMode': journal.single.values.first,
    'foreignKeys': foreignKeys.single.values.first == 1,
  };
}

void _printRollback(
  String command,
  DbRollbackResult result, {
  required bool json,
  required SqliteLoomCliPrinter printLine,
}) {
  if (json) {
    _printJson(printLine, {
      'command': command,
      'success': true,
      'rolledBack': result.rolledBack.map(_migrationJson).toList(),
    });
  } else if (result.rolledBack.isEmpty) {
    printLine('Nothing to rollback.');
  } else {
    for (final migration in result.rolledBack) {
      printLine('Rolled back ${migration.version} ${migration.name}');
    }
  }
}

Map<String, Object?> _migrationJson(DbMigration migration) => {
  'version': migration.version,
  'name': migration.name,
  'checksum': migration.checksum,
};
