name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ['3.12.0', stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: dart test
      - if: matrix.os == 'ubuntu-latest' && matrix.sdk == 'stable'
        run: dart run benchmark/bulk_writes.dart 10000 10000
      - if: matrix.os == 'ubuntu-latest' && matrix.sdk == 'stable'
        run: dart doc
